src/Entity/Page.php
<?php

namespace Score\PageBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Score\BaseBundle\Entity\BaseEntity;
use Score\PageBundle\Entity\PageBlock;

/**
 * @ORM\Entity(repositoryClass="Score\PageBundle\Entity\PageRepository")
 * @ORM\Table(name="cms_page")
 * @ORM\HasLifecycleCallbacks()
 */
class Page extends BaseEntity {


    /**
     * @ORM\Column(type="string", length=200)
     */
    protected $name;

    /**
     * @ORM\Column(name="title", type="string", length=200)
     */
    protected $title;

    /**
     * @ORM\Column(type="string", length=200, nullable = true)
     */
    protected $linkName;

    /**
     * @ORM\ManyToOne(targetEntity="Page")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
     */
    protected $parentPage;

    /**
     * @ORM\Column(type="integer", nullable = true)
     */
    protected $lvl;

    /**
     * @ORM\Column(type="integer", nullable = true)
     */
    protected $sortOrder;

    /**
     * @ORM\Column(type="string", length=255, nullable = true)
     */
    protected $seoId;

    /**
     * @ORM\Column(name="content", type="text", length=10000, nullable = true)
     */
    protected $content;

    /**
     * @ORM\Column(type="string", length=100, nullable = true)
     */
    protected $status;



    /**
     * @ORM\Column(type="string", nullable = true)
     */
    protected $lang;

    /**
     * @ORM\Column(type="integer", nullable = true)
     */
    protected $parentId;

    /**
     * @ORM\OneToMany(targetEntity="PageBlock", mappedBy="page")
     */
    private $pageBlocks;

    /**
     * @ORM\Column(name="config_data", type="text", length=10000, nullable = true)
     */
    protected $configData;

    /**
     * @ORM\Column(type="string", length=100, nullable = true)
     */
    protected $layout;

    /*//*
     * // //@--ORM\OneToMany(targetEntity="\KeywordBundle\Entity\KeywordItemPage", mappedBy="page")
     *///
    private $keywordItemPage;

    /**
     * @ORM\Column(type="string", length=2000, nullable = true)
     */
    protected $redirectUrl;

    /**
     * @ORM\Column(type="string", length=100, nullable = true)
     */
    protected $redirectWindow;

    /**
     * @ORM\Column(type="string", length=255, nullable = true)
     */
    protected $icon;

    /**
     * @ORM\Column(type="string", length=2000, nullable = true)
     */
    protected $teaser;


     /**
     * @ORM\OneToMany(targetEntity="\Score\CmsBundle\Entity\Multisite\SiteItemPage", mappedBy="page",cascade={"persist","remove"})
     */
    private $siteItemPage = [];

    private $multisite;


    public function getKeywordItemPage()
    {
        return $this->keywordItemPage;
    }

    public function setKeywordItemPage($keywordItemPage)
    {
        $this->keywordItemPage = $keywordItemPage;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    public function getLayout()
    {
        return $this->layout;
    }

    public function setLayout($layout)
    {
        $this->layout = $layout;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Page
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
    /**
     * Set title
     *
     * @param string $title
     * @return Page
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set linkName
     *
     * @param string $linkName
     * @return Page
     */
    public function setLinkName($linkName)
    {
        $this->linkName = $linkName;

        return $this;
    }

    /**
     * Get linkName
     *
     * @return string
     */
    public function getLinkName()
    {
        return $this->linkName;
    }

    /**
     * Set lvl
     *
     * @param integer $lvl
     * @return Page
     */
    public function setLvl($lvl)
    {
        $this->lvl = $lvl;

        return $this;
    }

    /**
     * Get lvl
     *
     * @return integer
     */
    public function getLvl()
    {
        return $this->lvl;
    }

    /**
     * Set sortOrder
     *
     * @param integer $sortOrder
     * @return Page
     */
    public function setSortOrder($sortOrder)
    {
        $this->sortOrder = $sortOrder;

        return $this;
    }

    /**
     * Get sortOrder
     *
     * @return integer
     */
    public function getSortOrder()
    {
        return $this->sortOrder;
    }

    /**
     * Set seoId
     *
     * @param string $seoId
     * @return Page
     */
    public function setSeoId($seoId)
    {
        $this->seoId = $seoId;

        return $this;
    }

    /**
     * Get seoId
     *
     * @return string
     */
    public function getSeoId()
    {
        return $this->seoId;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return Page
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set status
     *
     * @param string $status
     * @return Page
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }



    /**
     * Set lang
     *
     * @param string $lang
     * @return Page
     */
    public function setLang($lang)
    {
        $this->lang = $lang;

        return $this;
    }

    /**
     * Get lang
     *
     * @return string
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     * Set parentPage
     *
     * @param Page $parentPage
     * @return Page
     */
    public function setParentPage(Page $parentPage = null)
    {
        $this->parentPage = $parentPage;

        return $this;
    }

    /**
     * Get parentPage
     *
     * @return Page
     */
    public function getParentPage()
    {
        return $this->parentPage;
    }

    function getParentId()
    {
        return $this->parentId;
    }

    function setParentId($parentId)
    {
        $this->parentId = $parentId;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->pageBlocks = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add pageBlocks
     *
     * @param PageBlock $pageBlocks
     * @return Page
     */
    public function addPageBlock(PageBlock $pageBlocks)
    {
        $this->pageBlocks[] = $pageBlocks;

        return $this;
    }

    public function resetPageBlocks()
    {
        $this->pageBlocks = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Remove pageBlocks
     *
     * @param PageBlock $pageBlocks
     */
    public function removePageBlock(PageBlock $pageBlocks)
    {
        $this->pageBlocks->removeElement($pageBlocks);
    }

    /**
     * Get pageBlocks
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPageBlocks()
    {
        return $this->pageBlocks;
    }



    public function getRedirectUrl()
    {
        return $this->redirectUrl;
    }

    public function getRedirectWindow()
    {
        return $this->redirectWindow;
    }

    public function getIcon()
    {
        return $this->icon;
    }

    public function getTeaser()
    {
        return $this->teaser;
    }

    public function setRedirectUrl($redirectUrl)
    {
        $this->redirectUrl = $redirectUrl;
    }

    public function setRedirectWindow($redirectWindow)
    {
        $this->redirectWindow = $redirectWindow;
    }

    public function setIcon($icon)
    {
        $this->icon = $icon;
    }

    public function setTeaser($teaser)
    {
        $this->teaser = $teaser;
    }

    public function getLvlPrefix()
    {
        return str_repeat('- ', $this->getLvl() - 1);
    }

    public function hasLeftBar()
    {
        if ('menu-left-center-right' == $this->getLayout() or 'menu-left-center' == $this->getLayout())
        {
            return true;
        }
    }

    public function hasRightBar()
    {
        if ('menu-left-center-right' == $this->getLayout() or 'menu-center-right' == $this->getLayout())
        {
            return true;
        }
    }

    function getConfigData() {
        return $this->configData;
    }

    function setConfigData($configData): void {
        $this->configData = $configData;
    }




    /**
     * Get the value of siteItemPage
     */ 
    public function getSiteItemPage()
    {
        return $this->siteItemPage;
    }

    /**
     * Set the value of siteItemPage
     *
     * @return  self
     */ 
    public function setSiteItemPage($siteItemPage)
    {
        $this->siteItemPage = $siteItemPage;

        return $this;
    }

    /**
     * Get the value of multisite
     */ 
    public function getMultisite()
    {
        return $this->multisite;
    }

    /**

src/Resources/views/Admin/_block.html.twig
<li id="item_{{ pageBlock.id }}" class="dd-item" data-block-id="{{ pageBlock.block.id }}">
    <div class="dd-item-wrap">
        <a href="#" class="remove-block-trigger btn btn-sm btn-danger pull-right">
            {{ 'score.page.edit.block.delete'|trans }}
        </a>         <span class="dd-handle">
        {{ pageBlock.block.name }}
        </span>
        <div class="menu-item-edit-block" id="menu-item-edit-block-{{ pageBlock.id }}">
            <input type="hidden" name="page_blocks[{{ place }}][]" value="{{ pageBlock.block.id }}"/>
            <div class="box-body clear">
            </div>
        </div>
    </div>
</li>

src/Resources/views/Admin/_blockForm.html.twig
<form action="{{path('score_cms_page_edit_blocks')}}" method="post">
    <input type="hidden" name="id" id="page_id"  value="{{page.id}}"/>
    {% for group in groups %}
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">{{ group.name }}</h3>
            </div>

            <div class="box-body">
                <ul class="todo-list ui-sortable">
                    {% for block in group.blocks %}
                        <li id="block_{{block.id}}">
                            <!-- drag handle -->

                            <!-- checkbox -->
                            <input type="checkbox" value="{{block.id}}" name="page_blocks[]" {% if block.id in pageBlocks|keys %}checked="checked"{% endif %}>
                            <!-- todo text -->
                            <span class="text">{{block.name}}</span>

                            <select name="place[{{block.id}}]">
                                <option value="left" {% if block.id in pageBlocks|keys and pageBlocks[block.id].place == 'left' %}selected="selected"{% endif %}>vľavo</option>
                                <option value="center" {% if block.id in pageBlocks|keys and  pageBlocks[block.id].place == 'center' %}selected="selected"{% endif %}>stred</option>
                                <option value="right" {% if block.id in pageBlocks|keys and  pageBlocks[block.id].place == 'right' %}selected="selected"{% endif %}>vpravo</option>
                            </select>
                            <!-- Emphasis label -->
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="box-footer">

            </div>
        </div>
    {% endfor %}
    <button class="btn btn-success" type="submit">{{'score.page.edit.save'|trans}}</button>
</form>

src/Resources/views/Admin/_blocks.html.twig
<form action="{{ path('score_cms_page_edit_blocks') }}" method="post">
    <input type="hidden" name="id" id="page_id" value="{{ page.id }}"/>

    <div class="row">
        <div class="col-sm-12">
            <h2>
                {{ 'score.page.edit.block.title'|trans }}
            </h2>
            <div class="row {{ page.layout }}">
                <!-- left bar -->
                {% if page.hasLeftBar %}
                    <div class="cms-left">
                        <h3>
                            {{ 'score.page.edit.block.leftPlace.title'|trans }}
                        </h3>
                        <div class="dd">
                            <ol id="block-left" class="dd-list" data-count="{{ page.pageBlocks | length }}">
                                {% for pageBlock in page.pageBlocks %}
                                    {% if pageBlock.place is same as 'left' %}
                                        {{ include('@ScorePage/Admin/_block.html.twig',{'pageBlock': pageBlock,'place':'left'}) }}
                                    {% endif %}
                                {% endfor %}
                            </ol>
                        </div>
                        <div class="add-block">
                            <a data-target="left" href="#"
                               class="btn btn-success">
                                {{ 'score.page.edit.block.add'|trans }}
                            </a>
                        </div>
                    </div>
                {% endif %}


                <!--center bar-->
                <div class="cms-center">
                    <h3>
                        {{ 'score.page.edit.block.centerPlace.title'|trans }}
                    </h3>
                    <div class="dd">
                        <ol id="block-center" class="dd-list" data-count="{{ page.pageBlocks | length }}">
                            {% for pageBlock in page.pageBlocks %}
                                {% if 'center' is same as pageBlock.place %}
                                    {{ include('@ScorePage/Admin/_block.html.twig',{'pageBlock': pageBlock,'place':'center'}) }}
                                {% endif %}
                            {% endfor %}
                        </ol>
                    </div>
                    <div class="add-block">
                        <a data-target="center" href="#"
                           class="btn btn-success">
                            {{ 'score.page.edit.block.add'|trans }}
                        </a>
                    </div>
                </div>

                <!-- right bar -->
                {% if page.hasRightBar %}
                    <div class="cms-right">
                        <h3>
                            {{ 'score.page.edit.block.rightPlace.title'|trans }}
                        </h3>
                        <div class="dd">
                            <ol id="block-right" class="dd-list" data-count="{{ page.pageBlocks | length }}">
                                {% for pageBlock in page.pageBlocks %}
                                    {% if 'right' is same as pageBlock.place %}
                                        {{ include('@ScorePage/Admin/_block.html.twig',{'pageBlock': pageBlock,'place':'right'}) }}
                                    {% endif %}
                                {% endfor %}
                            </ol>
                        </div>
                        <div class="add-block">
                            <a data-target="right" href="#"
                               class="btn btn-success">
                                {{ 'score.page.edit.block.add'|trans }}
                            </a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="overlay-modal">
        <div>
            <div class="close-wrapper">
                <a href="#" class="close-overlay">
                    <i class="fa fa-times"></i>
                </a>
            </div>
            <h2>
                {{ 'score.page.edit.block.available.topTitle'|trans }}
            </h2>
            <table id="page-blocks-datatable" class="table table-striped display compact" data-position="">
                <thead>
                <tr>
                    <th>{{ 'score.page.edit.block.available.name'|trans }}</th>
                    <th>{{ 'score.page.edit.block.available.type'|trans }}</th>
                    <th></th>
                </tr>
                </thead>
                <tbody class="ui-sortable">
                {% for blockItem in availableBlocks %}
                        <tr>
                            <td>
                                {{ blockItem.name }}
                            </td>
                            <td>
                                {{ blockItem.type }}
                            </td>
                            <td>
                                <a href="#" data-id="{{ blockItem.id }}" data-name="{{ blockItem.name }}">{{ "score.page.edit.block.add" | trans }}</a>
                            </td>
                        </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <button class="btn btn-success btn-lg" type="submit">
        {{ 'score.page.edit.save'|trans }}
    </button>
</form>

src/Resources/views/Admin/_blocksOrganization.html.twig
<form action="{{path('score_cms_page_edit_blocks')}}" method="post">
    <input type="hidden" name="id" id="page_id"  value="{{page.id}}"/>

    {#
    <iframe style="width: 100%; min-height: 800px">
        {{ include('@Content/Default/subpage.html.twig',{'page': page}) }}
    </iframe>
    #}

    <div class="blocks-wrapper {{page.layout}}">
        {% if page.hasLeftBar %}
            <div class="left-sidebar">

                {% for pageBlock in page.pageBlocks %}
                    {% if 'left' == pageBlock.place %}
                        <h2>{{ pageBlock.block.name }}</h2>
                        {{ include('@Content/Default/_block.html.twig',{'pageBlock': pageBlock}) }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}


        <div class="main-content">
            {{ page.content|raw }}
        </div>

        {% if page.hasRightBar %}
            <div class="right-sidebar">
                {% for pageBlock in page.pageBlocks %}
                    {% if 'right' == pageBlock.place %}
                        <h2>{{ pageBlock.block.name }}</h2>
                        {{ include('@Content/Default/_block.html.twig',{'pageBlock': pageBlock}) }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}

    </div>



    {{ dump(page.layout) }}
    {{ dump(pageBlocks) }}

    <button class="btn btn-success" type="submit">{{'score.page.edit.save'|trans}}</button>
</form>

src/Resources/views/Admin/_contentForm.html.twig
{{ form_start(form) }}
<div class="row">
	{{ form_errors(form) }}
	<div class="col-sm-9">

		{{ form_row(form.name) }}


		<div class="row">
			<div class="col-sm-5">
				{{ form_row(form.title) }}
			</div>
			<div class="col-sm-5">
				<div class="form-group">
					{{ form_label(form.seo_id) }}
					{{ form_errors(form.seo_id) }}<br/>
					{{ domain }}
					/
					{{ form_widget(form.seo_id,{'attr':{'style':'display:inline-block; max-width:70%; padding-left:2px;'}}
					) }}
				</div>
			</div>
			<div class="col-sm-2 text-right">
				{% if page.id > 0 %}
					<a style="margin-top:25px;" class="btn btn-info open-window-trigger" href="{{ path('subpage_preview',{'id' : page.id}) }}">{{ 'score.page.edit.preview'|trans }}</a>
				{% endif %}
			</div>
		</div>


		<div class="form-group">
			{{ form_row(form.content,{'id':'test'}) }}
		</div>
	</div>

	<div
		class="col-sm-3">
		<!-- PARENT PAGE -->
		<div class="form-group">
			<label for="parent_page">{{ 'score.page.edit.parentPage'|trans }}</label>
			<select name="parent_page" id="parent_page" class="form-control">
				<option value="">{{ 'score.page.edit.emptyParent'|trans }}</option>
				{% for parentPage in parentPages %}
					<option {% if parentPage.id == page.parentId %} selected="selected" {% endif %} value="{{ parentPage.id }}">{{ parentPage.lvlPrefix }}
						{{ parentPage.name }}</option>
				{% endfor %}
			</select>
		</div>

		<!-- PAGE VISIBILITY -->
		{{ form_row(form.status) }}

		<!-- PAGE LAYOUT -->
		{{ form_row(form.layout) }}

        
		{% if form.multisite.vars.choices| length  > 0 %}
			<div class="form-group">
				{{ form_row(form.multisite) }}
			</div>
		{% endif %}


        <h3>{{ 'score.page.edit.subpages'|trans }}</h3>
		{% if subpages | length %}
			
			<ul>
				{% for subpage in subpages %}
					<li>
						<a href="{{ path('score_cms_page_edit', {'id': subpage.id}) }}">{{ subpage.name }}</a>
					</li>
				{% endfor %}
			</ul>
		{% else %}
			<h5>{{ 'score.page.edit.noSubpages'|trans }}</h5>
		{% endif %}



		{% if logs is defined and logs | length %}
			<h3>{{ 'score.block.edit.log.title'|trans }}</h3>
			<ul class="log-list">
				{% for log in logs %}
					<li>
						<a href="#" title="[Zmena-{{ log.id }}]" data-content="{{ log.oldValue }}">{{ log.createdAt | date("d. m. Y - H:i") }}</a>
					</li>
				{% endfor %}
			</ul>
		{% else %}
			<h5>{{ 'score.block.edit.log.noLog'|trans }}</h5>
		{%  endif %}


	</div>


</div>

<button type="submit" class="btn btn-success btn-lg">{{ 'score.page.edit.save'|trans }}</button>
<a class="btn btn-danger btn-sm" href="">{{ 'score.page.edit.cancel'|trans }}</a>
{{ form_end(form) }}

src/Resources/views/Admin/_delete_modal.html.twig
<div class="modal fade" id="confirm-delete-page-modal" tabindex="-1" role="dialog" aria-label="{{'score.page.delete.title'|trans}}">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">{{'score.page.delete.title'|trans}}</h4>
      </div>
      <div class="modal-body">

        <p>{{'score.page.delete.confirm'|trans}}</p>

      </div>

      <div class="modal-footer">
        <a class="btn btn-success" href="#">{{'score.page.delete.yes'|trans}}</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">{{'score.page.delete.cancel'|trans}}</button>
      </div>
    </div>
  </div>
</div>

src/Resources/views/Admin/_js.html.twig
 <script src="{{ asset('bundles/scorecms/plugins/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('bundles/scorecms/plugins/ckeditor/config.js') }}?v=1"></script>
    <script src="{{ asset('bundles/scorecms/plugins/slugify/slugify.js') }}"></script>
    <script src="{{ asset('bundles/scorecms/plugins/jQueryUI/jquery-ui.min.js') }}"></script>
    <script type="text/javascript">
        var roxyFileman = '/bundles/scorecms///plugins/fileman/index.html';
        $(function () {
            CKEDITOR.replace('test', {filebrowserBrowseUrl: roxyFileman,
                filebrowserImageBrowseUrl: roxyFileman + '?type=image',
                removeDialogTabs: 'link:upload;image:upload'});


                //CKEDITOR.config.contentsCss = '/idsk/css/main.css' ;  
        });

        $('#page_form_name').on('keydown', function () {
            var slug = url_slug($('#page_form_name').val());
            if ($('#page_form_seo_id').val() == '')
            {
                $('#page_form_seo_id').val(slug);
            }
        });
    </script>

src/Resources/views/Admin/create.html.twig
{% extends '@ScoreCms/Default/adminLayout.html.twig' %}
{% block content_header_title %}
    <h1>{{'score.page.create.title'|trans}} </h1>
{% endblock %}

{% block content_header_breadcrumb %}
    {{ parent() }}
     <li class="active">{{ 'score.page.create.breadcrumb' | trans }}</li>
{% endblock %}


{% block body%}
    {% for flash_message in app.session.flashBag.get('score_cms_page_edit_success') %}
    <div class="alert alert-success">
        {{ flash_message|trans }}
    </div>
{% endfor %}



  <div class="nav-tabs-custom">
        <ul class="nav nav-tabs" role="tablist">
            <li {% if activeSection == 'page' %}class="active"{% endif %}><a href="#tab_1" data-toggle="tab" >{{'score.page.create.content'|trans}}</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane{% if activeSection == 'page' %} active{% endif %}" id="tab_1">
              {{ include('@ScorePage/Admin/_contentForm.html.twig', { 'form': form, 'parentPages':parentPages}) }}
            </div><!-- /.tab-pane -->

        </div><!-- /.tab-content -->
    </div>


{% endblock %}




{% block javascripts %}
    {{ parent() }}
    {{ include('@ScorePage/Admin/_js.html.twig', { 'page':page}) }}
{% endblock %}

src/Resources/views/Admin/index.html.twig
{% extends '@ScoreCms/Default/adminLayout.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/scorecms/plugins/datatables/datatables.min.css') }}" rel="stylesheet"/>
{% endblock %}

{% block content_header_title %}
    <h1>{{ 'score.page.list.topTitle'|trans }} </h1>
{% endblock %}

{% block content_header_breadcrumb %}
    {{ parent() }}
    <li class="active">{{ 'score.page.list.breadcrumb' | trans }}</li>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-10">
            <div class="box box-solid">
                <div class="box-body">
                    <table id="pages-datatable" class="table table-striped display compact">
                        <thead>
                        <tr>
                            <th>{{ 'score.page.list.name'|trans }}</th>

                            <th>{{ 'score.page.list.action'|trans }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for page in list %}
                            <tr>
                                <td>
                                    <a class="lvl_{{ page.lvl }}"
                                       href="{{ path('score_cms_page_edit',{id:page.id}) }}">{{ page.lvlPrefix }} {{ page.name }}</a>
                                </td>
                                <td>
                                    <a class="delete-page"
                                       href="{{ path('score_cms_page_delete',{id:page.id}) }}">{{ 'score.page.list.delete'|trans }}</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="box-footer clearfix">

                </div>
            </div>
        </div>

        <div class="col-sm-2">
            <div class="box box-primary">
                <div class="box-body">

                    <a href="{{ path('score_cms_page_create',{parent_id:0}) }}"
                       class="btn btn-primary">{{ 'score.page.list.create'|trans }} </a>


                </div>
            </div>
        </div>
    </div>


    {{ include('@ScorePage/Admin/_delete_modal.html.twig') }}

{% endblock %}


    {% block javascripts %}
        {{ parent() }}
        <script src="{{ asset('bundles/scorecms/plugins/jQueryUI/jquery-ui.min.js') }}"></script>
        <script src="{{ asset('bundles/scorecms/plugins/datatables/datatables.min.js') }}"></script>
        <script src="{{ asset('bundles/scorepage/js/PageManager.js') }}"></script>
        <script type="text/javascript">

            $('#pages-datatable').DataTable({
                language: {
                    url: {{ asset('bundles/scorecms/plugins/datatables/'~ lang ~'.js') }}
                },
                "ordering": false
            });


            /*
             var page_manager = new PageManager();
             page_manager.reorder_pages_url_url = '{{ path('score_cms_page_subpages_reorder') }}';
             page_manager.bindTriggers();

             $(".ui-sortable").sortable({
             update: function (event, ui) {
             var sorted = $(this).sortable("serialize");
             page_manager.reorderPages(sorted);
             }
             });
    */

        </script>

        <script>

            $('body').on('click', '.delete-page', function (e) {
                e.preventDefault();
                $('#confirm-delete-page-modal .btn-success').attr('href', $(this).attr('href'));
                $('#confirm-delete-page-modal').modal('show');
            });
        </script>
    {% endblock %}